# Enable EEPROM subsystem
CONFIG_EEPROM=y

# Enable microconf module
CONFIG_MICROCONF=y
CONFIG_MICROCONF_BACKEND_EEPROM=y

# Enable Zephyr Shell with microconf commands
CONFIG_SHELL=y
CONFIG_MICROCONF_SHELL=y

# Logging
CONFIG_LOG=y
CONFIG_MICROCONF_LOG_LEVEL_INF=y
