# Enable Flash Map subsystem
CONFIG_FLASH=y
CONFIG_FLASH_MAP=y

# Enable microconf module with Flash backend
CONFIG_MICROCONF=y
CONFIG_MICROCONF_BACKEND_FLASH=y

# Enable Zephyr Shell
CONFIG_SHELL=y
CONFIG_MICROCONF_SHELL=y

# Logging
CONFIG_LOG=y
CONFIG_MICROCONF_LOG_LEVEL_INF=y
